<!-- PREPEND - название страницы перед названием сайта в title -->
<?php $this->headTitle('Main page', 'PREPEND');
      $this->headMeta()->appendName('keywords', 'ZF, PHP')
                       ->appendName('description', 'ZF learn');
      ?>

<?php
   $url = $this->url(array('controller' => 'index', 'action' => 'index', 'a' => 333), 'default');
?>
<a href="<? echo $url?>">Category</a>

<p><? echo $this->a ?></p>